# Generated by Django 5.2.4 on 2025-09-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_file_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="is_permanent",
            field=models.BooleanField(default=False, verbose_name="Постоянный файл"),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(fields=["code"], name="files_file_code_5ff5cc_idx"),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["is_deleted", "expires_at"],
                name="files_file_is_dele_648c0c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["download_count"], name="files_file_downloa_da04f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["created_at"], name="files_file_created_22ed95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["file_size"], name="files_file_file_si_ed220e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["is_protected"], name="files_file_is_prot_84ef1e_idx"
            ),
        ),
    ]
