# Generated by Django 5.2.4 on 2025-09-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_file_is_permanent_file_files_file_code_5ff5cc_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="compressed_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="compressed_pdfs/",
                verbose_name="Сжатый PDF",
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="compressed_pdf_size",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Размер сжатого PDF (байт)"
            ),
        ),
    ]
